version: '3.7'

services:
  automoderator-canary-discord-proxy:
    image: chatsift/automoderator:v3
    env_file:
      - ./.env.automoderator-v3
    restart: unless-stopped
    expose:
      - 8000
    command: ['node', '--enable-source-maps', 'services/discord-proxy/dist/index.js']

  automoderator-canary-gateway:
    image: chatsift/automoderator:v3
    env_file:
      - ./.env.automoderator-v3
    restart: unless-stopped
    command: ['node', '--enable-source-maps', 'services/gateway/dist/index.js']

  automoderator-canary-interactions:
    image: chatsift/automoderator:v3
    env_file:
      - ./.env.automoderator-v3
    restart: unless-stopped
    command: ['node', '--enable-source-maps', 'services/interactions/dist/index.js']

  automoderator-canary-logging:
    image: chatsift/automoderator:v3
    env_file:
      - ./.env.automoderator-v3
    restart: unless-stopped
    command: ['node', '--enable-source-maps', 'services/logging/dist/index.js']

  automoderator-canary-task-runner:
    image: chatsift/automoderator:v3
    env_file:
      - ./.env.automoderator-v3
    restart: unless-stopped
    command: ['node', '--enable-source-maps', 'services/task-runner/dist/index.js']
