version: '3.7'

services:
  roles-bot:
    image: chatsift/roles:latest
    env_file:
      - ./.env.roles
    environment:
      DATABASE_URL: 'postgresql://user:admin@postgres:5432/roles'
    restart: unless-stopped
    volumes:
      - ./logs/roles:/usr/roles/logs
    depends_on:
      - postgres
    command:
      [
        'node',
        '--es-module-specifier-resolution=node',
        '--enable-source-maps',
        '--no-warnings',
        './packages/bot/dist/index.js',
      ]
