version: '3.7'

services:
  social-bot:
    image: chatsift/social:latest
    env_file:
      - ./.env.social
      - ./.env.parseable
    environment:
      DATABASE_URL: 'postgresql://user:admin@postgres-old:5432/social'
      REDIS_URL: 'redis://redis:6379/1'
      SERVICE_NAME: 'socialbot'
    restart: unless-stopped
    volumes:
      - ./logs/social:/usr/social/logs
    command: 'sh -c "yarn prisma migrate deploy && (node --enable-source-maps ./packages/bot/dist/index.js 2>&1 | node --enable-source-maps ./node_modules/.bin/chatsift-logs)"'
