version: '3.7'

services:
  social-bot:
    image: chatsift/social:latest
    env_file:
      - ./.env.social
      - ./.env.parseable
    environment:
      DATABASE_URL: 'postgresql://user:admin@postgres:5432/social'
      REDIS_URL: 'redis://redis:6379/1'
      SERVICE_NAME: 'social-bot'
    restart: unless-stopped
    volumes:
      - ./logs/social:/usr/social/logs
    command: 'node --enable-source-maps ./packages/bot/dist/index.js 2>&1 | node --enable-source-maps ./node_modules/.bin/chatsift-logs'

  social-api:
    image: chatsift/social:latest
    env_file:
      - ./.env.social
      - ./.env.parseable
    environment:
      DATABASE_URL: 'postgresql://user:admin@postgres:5432/social'
      PORT: '8080'
      SERVICE_NAME: 'social-api'
    expose:
      - 8080
    restart: unless-stopped
    volumes:
      - ./logs/social:/usr/social/logs
    command: 'node --enable-source-maps ./packages/api/dist/index.js 2>&1 | node --enable-source-maps ./node_modules/.bin/chatsift-logs'
